import PDFDocument from "pdfkit";
import { uploadPdf } from "./uploader.js";

export const generatePdf = (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
      });

      const chunks = [];

      doc.on("data", (chunk) => {
        chunks.push(chunk);
      });

      doc.on("error", reject);

      doc.on("end", async () => {
        try {
          const pdfBuffer = Buffer.concat(chunks);

          if (!pdfBuffer.length) {
            throw new Error("Generated PDF is empty");
          }

          const filename =
            data.title
              ?.toLowerCase()
              .replace(/[^a-z0-9]+/g, "-")
              .replace(/^-|-$/g, "") ||
            `document-${Date.now()}`;

          const result = await uploadPdf(
            filename,
            pdfBuffer,
            "application/pdf",
          );

          resolve({
            url: result.secure_url,
            publicId: result.public_id,
            filename: `${filename}.pdf`,
          });
        } catch (error) {
          reject(error);
        }
      });

      // =========================
      // TITLE
      // =========================

      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .fillColor("#000000")
        .text(data.title || "Document", {
          align: "center",
        });

      doc.moveDown(0.5);

      // =========================
      // SUBTITLE
      // =========================

      if (data.subtitle) {
        doc
          .fontSize(12)
          .font("Helvetica")
          .text(data.subtitle, {
            align: "center",
          });

        doc.moveDown(1.5);
      } else {
        doc.moveDown(1);
      }

      // =========================
      // SECTIONS
      // =========================

      if (Array.isArray(data.sections)) {
        data.sections.forEach((section, index) => {
          doc
            .fontSize(16)
            .font("Helvetica-Bold")
            .text(
              `${index + 1}. ${
                section.heading || "Section"
              }`,
            );

          doc.moveDown(0.5);

          if (Array.isArray(section.points)) {
            section.points.forEach((point) => {
              doc
                .fontSize(11)
                .font("Helvetica")
                .text(`• ${point}`, {
                  indent: 15,
                  paragraphGap: 6,
                });
            });
          }

          doc.moveDown(1);
        });
      }

      // =========================
      // FOOTER + PAGE NUMBERS
      // (on every page)
      // =========================

      const range = doc.bufferedPageRange();

      for (
        let pageNumber = range.start;
        pageNumber < range.start + range.count;
        pageNumber++
      ) {
        doc.switchToPage(pageNumber);

        // 👇 Save current bottom margin
        const oldBottomMargin = doc.page.margins.bottom;

        // 👇 Disable bottom margin so pdfkit doesn't
        //    auto-create a new blank page
        doc.page.margins.bottom = 0;

        // ---------- FOOTER TEXT (centered) ----------
        doc
          .fontSize(9)
          .font("Helvetica")
          .fillColor("#9CA3AF")
          .text(
            "Generated By AgentixAI",
            50,
            doc.page.height - 55,
            {
              width: doc.page.width - 100,
              align: "center",
              lineBreak: false,
            },
          );

        // ---------- PAGE NUMBER (below footer) ----------
        doc
          .fontSize(9)
          .font("Helvetica")
          .fillColor("#9CA3AF")
          .text(
            `Page ${pageNumber + 1} of ${range.count}`,
            50,
            doc.page.height - 35,
            {
              width: doc.page.width - 100,
              align: "center",
              lineBreak: false,
            },
          );

        // 👇 Restore original bottom margin
        doc.page.margins.bottom = oldBottomMargin;
      }

      // =========================
      // FINISH
      // =========================

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};